### ISSUE TITLE
import failure on alpha_release branch

### ISSUE THREAD

**Issue by Balandat** [jrg365/gpytorch#68] opened 2018-01-26 01:00 UTC
The following import error happens on the alpha_release branch (relevant changes here: https://github.com/jrg365/gpytorch/commit/935fca907a495a282c8c760fdb2567e4e1a7fe04)

```
import gpytorch
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-72157b85bfdf> in <module>()
----> 1 import gpytorch

/data/users/balandat/fbsource/fbcode/buck-out/dev-nosan/gen/bento/kernels/bento_kernel_ae_dev#link-tree/gpytorch/__init__.py in <module>()
      1 from .module import Module
----> 2 import models
      3 import means
      4 import kernels
      5 from torch.autograd import Variable

ModuleNotFoundError: No module named 'models'
```

**Comment by jrg365** [comment] 2018-01-26 01:42
@gpleiss Looks like there are some python 3 compatibility that slipped by us because Travis isn't running on the alpha release branch and we both happen to have been using python 2 recently. I'm looking at fixing them now.

A lazy way to get Travis running the tests on the alpha branch would be to just make a PR for it.

**Comment by jrg365** [comment] 2018-01-26 01:48
Okay, looks like it was just those three import statements luckily -- I am closing this since (1) I was able to reproduce the issue, but (2) all tests now pass for me in both python 2 and python 3.

**Closed by jrg365** 2018-01-26 01:48 UTC

**Comment by Balandat** [comment] 2018-01-26 02:32
great, thanks for the fix
